# Generated by Django 6.0.4 on 2026-04-16 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('nome', models.CharField(max_length=120)),
                ('carga_horaria_semana', models.PositiveIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('hora_inicio_intervalo', models.TimeField()),
                ('hora_fim_intervalo', models.TimeField()),
                ('jornada_personalizada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'jornada',
                'constraints': [models.UniqueConstraint(fields=('empresa_id', 'nome'), name='uniq_jornada_nome_por_empresa'), models.CheckConstraint(condition=models.Q(('carga_horaria_semana__gt', 0)), name='ck_jornada_carga_maior_que_zero')],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='workforce.workschedule')),
            ],
            options={
                'db_table': 'colaborador',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('perfil', models.CharField(choices=[('MESTRE', 'Mestre'), ('ADMIN', 'Admin'), ('COLABORADOR', 'Colaborador')], max_length=20)),
                ('empresa_id', models.UUIDField(db_index=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('colaborador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='workforce.collaborator')),
            ],
            options={
                'db_table': 'usuario',
                'constraints': [models.UniqueConstraint(condition=models.Q(('perfil', 'MESTRE')), fields=('empresa_id',), name='uniq_usuario_mestre_por_empresa'), models.CheckConstraint(condition=models.Q(models.Q(('colaborador__isnull', True), ('perfil', 'MESTRE')), models.Q(('colaborador__isnull', False), ('perfil__in', ['ADMIN', 'COLABORADOR'])), _connector='OR'), name='ck_usuario_perfil_colaborador')],
            },
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('empresa_id', 'matricula'), name='uniq_colaborador_matricula_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('empresa_id', 'email'), name='uniq_colaborador_email_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('empresa_id', 'cpf'), name='uniq_colaborador_cpf_por_empresa'),
        ),
    ]
