# Generated by Django 6.0.4 on 2026-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', help_text='Timezone IANA da empresa para regras temporais de dominio.', max_length=64),
        ),
    ]
