# Generated by Django 6.0.4 on 2026-04-16 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeadjustmentrequest',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeadjustmentrequest',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_ajuste', to='workforce.collaborator'),
        ),
        migrations.AddField(
            model_name='timeadjustmentrequest',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pontos', to='workforce.collaborator'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='ponto_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='attendance.timeentry'),
        ),
        migrations.AddField(
            model_name='timeadjustmentrequest',
            name='ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='attendance.timeentry'),
        ),
        migrations.AddField(
            model_name='timeadjustmentrequest',
            name='ponto_resultante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_resultantes', to='attendance.timeentry'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['colaborador', '-data_hora'], name='ponto_colabor_e9e6f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(fields=('colaborador', 'data_hora', 'ativo'), name='uniq_ponto_colaborador_data_hora_ativo'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_ponto', 'ENTRADA'), ('tipo_ponto', 'SAIDA'), _connector='OR'), name='ck_ponto_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='timeadjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDENTE', 'APROVADO', 'REJEITADO'])), name='ck_solicitacao_status_valido'),
        ),
    ]
