# Generated by Django 6.0.4 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeadjustmentrequest",
            name="ativo",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
