# Generated by Django 6.0.4 on 2026-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_timeadjustmentrequest_ativo'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='gerado_automaticamente',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='motivo_geracao',
            field=models.CharField(blank=True, choices=[('', 'Nenhum'), ('AUTO_FECHAMENTO_24H', 'Auto fechamento 24h')], default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gerado_automaticamente', False), ('motivo_geracao', '')), models.Q(('gerado_automaticamente', True), ('motivo_geracao__gt', '')), _connector='OR'), name='ck_ponto_geracao_automatica_consistente'),
        ),
    ]
